import "./globals.css";
import { Roboto, Inter } from 'next/font/google';

const roboto = Roboto({
  weight: ['400', '500', '600', '700', '900'], 
  subsets: ['latin'], 
  variable: '--font-roboto', 
  display: 'swap', 
});

const inter = Inter({
  weight: ['400'], 
  subsets: ['latin'],
  variable: '--font-inter', 
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
